### ISSUE TITLE
BufferedInputSourceTest fails intermittently

### ISSUE THREAD

**Issue by Baltoli** [WildPetScience/Triton#13]
The test `uk.ac.cam.cl.wildpetscience.triton.lib.pipeline.BufferedInputSourceTest` fails on some compiles but not others.

**Comment by Baltoli** [comment]
Afraid this still fails sometimes:

`uk.ac.cam.cl.wildpetscience.triton.lib.pipeline.BufferedInputSourceTest > testBufferedInputSource FAILED
    java.lang.RuntimeException at BufferedInputSourceTest.java:52`

**Comment by w-shackleton** [comment]
:cry: flaky tests already. Will try to re-fix.
