### ISSUE TITLE
Decide on web framework

### ISSUE THREAD

**Issue by w-shackleton** [WildPetScience/Triton#5]
I really like the look of [Play](https://www.playframework.com/), but it doesn't seem to suit our needs that well - it's more aimed at writing a full fledged web application that runs on a webapp server and doesn't seem that flexible when it comes to integrating with other code or running as part of a bigger application - you also have to use their build system and project layout that doesn't suit our other needs. Since this server will be doing many things of which serving this website is a small one, I'd say we should use a more lightweight library.

Discuss.

**Comment by w-shackleton** [comment]
Some other suggestions:
- [Spark](http://sparkjava.com/)
- [Grails](https://grails.org/)

**Comment by Baltoli** [comment]
I like the look of Grails - it is supported on Heroku, which makes deployment of a server app easy. It's also supported in IDEA. 

The only real issue I can see is that it uses Groovy instead of Java, but apparently there's not much of a learning curve to switch to Groovy. @rogersnm what do you think?

**Comment by Baltoli** [comment]
That said, Spark looks like it might be easier to integrate (but more of a hassle to deploy, possibly)

**Comment by w-shackleton** [comment]
We could use Grails for server.

**Comment by Baltoli** [comment]
I'd be happy to write in Groovy for the local config site

**Comment by w-shackleton** [comment]
Same, but we should clear this with the whole team (supposed to use Java etc)

**Comment by Baltoli** [comment]
Agreed - Groovy is intended to have minimal cognitive overhead for Java developers, but there would still be some involved in using it.

@sashforth @antoanela @gavrilavlad @rogersnm @w-shackleton what are your thoughts?

**Comment by Baltoli** [comment]
Actually, having looked at it a bit more, I think Spark would be easier for my section (local config site), while Grails would probably do better for the server part.

**Comment by w-shackleton** [comment]
Cool, I'll add Spark to this project and create an issue in Condor.
