### ISSUE TITLE
Noise reduction is slow

### ISSUE THREAD

**Issue by Baltoli** [WildPetScience/Triton#60]
The demo for noise reduction is incredibly slow, even on relatively powerful hardware - this will be an issue when we want to do it on the Raspberry Pi. As I see it we have two options:
- Reduce the amount of noise reduction very dramatically
- Have our video taken at a much smaller resolution (which is possibly ok for movement detection)

**Comment by Baltoli** [comment]
Also @w-shackleton

**Comment by w-shackleton** [comment]
I'm working on making input resolution configurable.

**Comment by w-shackleton** [comment]
Also, we can import images straight into OpenCV in grayscale - this might help

**Comment by w-shackleton** [comment]
The plan is to make the recognition algorithms take noise into account.

**Comment by w-shackleton** [comment]
Did we actually solve this issue?

**Comment by Baltoli** [comment]
I did wonder if you'd get notified about this closing - as I recall the final product was extremely slow so I have no idea if that included a fix for this or not. Happy to reopen if you'd like to keep track of the project of course!
