### ISSUE TITLE
opencv.Rect internally uses int

### ISSUE THREAD

**Issue by w-shackleton** [WildPetScience/Triton#69]
and hence we need to write our own Rect class (positions between 0 and 1). @Baltoli you want to do this (and replace it throughout the code)? Simple methods like contains() would be nice.

**Comment by antoanela** [comment]
we can use this constructor public Rect(Point p1, Point p2), Point uses double

**Comment by w-shackleton** [comment]
That still casts to int internally.

**Comment by w-shackleton** [comment]
@antoanela want to take this on?

**Comment by w-shackleton** [comment]
We need it working for the demos to actually work (so it's high-pri)

**Comment by w-shackleton** [comment]
Ah there might be a Box class

**Comment by w-shackleton** [comment]
Box exists. Use box.

**Comment by w-shackleton** [comment]
I'll take this on now.

**Comment by w-shackleton** [comment]
Sorry about the confusion guys! We do have a Box class.
