### ISSUE TITLE
Sending data from AnalysisOutputSink

### ISSUE THREAD

**Issue by sashforth** [WildPetScience/Triton#83]
Is there a way to send the data back to the PositionTestPanel? This would allow us to draw a route of the (estimated) path of the animal in the demo.

This would strictly just be for the demo, of course.

**Comment by w-shackleton** [comment]
I don't see why not - create a method the Analysis interface, implement it, and then add some code to the draw method of PositionTestPanel that uses the data from the Analysis passed in.
